### ISSUE TITLE
Multiple Entry Points

### ISSUE THREAD

**Issue by Nishchit14** [trailsjs/trailpack-webpack#10]
Trails app crashes on multi entry point. (Original doc [here](https://webpack.github.io/docs/multiple-entry-points.html))

Webpack.js:

```
...
entry: [
      { admin: './src/react/index.js' }
    ],
 output: {
      path: path.join(__dirname, '../public/dist'),
      filename: '[name].bundle.js',
      publicPath: '/dist/'
    },
...
```

Trails app crash report

```
debug: trails event: trailpack:mongoose:initialized
error: 
 TypeError: request.replace is not a function
    at /home/nd/Desktop/trails-repo/node_modules/trailpack-webpack/node_modules/webpack/lib/NormalModuleFactory.js:72:27
    at /home/nd/Desktop/trails-repo/node_modules/trailpack-webpack/node_modules/webpack/lib/NormalModuleFactory.js:28:4
```

**Comment by Nishchit14** [comment]
I am sorry, its my silly mistake. i fix it.

Don't use [ ]

```
entry: [
      { admin: './src/react/index.js' }
    ]
```

Use { }

```
entry:  { 
       admin: './src/react/index.js' 
}
```
